const http = require("http");
const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");

const PORT = Number(process.env.PORT || 3000);
const ADMIN_USER = process.env.ADMIN_USER || "admin";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "admin123";
const SUPABASE_URL = process.env.SUPABASE_URL || "";
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY || "";
const USE_SUPABASE = Boolean(SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY);
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, "data");
const DB_FILE = process.env.DB_FILE || path.join(DATA_DIR, "db.json");
const SEED_GAMES_FILE = path.join(__dirname, "data", "seed-games.json");
const PUBLIC_DIR = path.join(__dirname, "public");
const sessions = new Map();
const defaultDb = { games: [], players: [], predictions: [] };
const mimeTypes = { ".html":"text/html; charset=utf-8", ".css":"text/css; charset=utf-8", ".js":"application/javascript; charset=utf-8", ".json":"application/json; charset=utf-8", ".svg":"image/svg+xml", ".png":"image/png", ".ico":"image/x-icon" };
async function ensureDb(){if(USE_SUPABASE){await readSupabaseDb();return}await fs.mkdir(DATA_DIR,{recursive:true});try{await fs.access(DB_FILE)}catch{await writeDb(await initialDb())}}
function normalizeDb(db){return{games:Array.isArray(db.games)?db.games:[],players:Array.isArray(db.players)?db.players:[],predictions:Array.isArray(db.predictions)?db.predictions:[]}}
async function initialDb(){try{const raw=await fs.readFile(SEED_GAMES_FILE,"utf8");const games=JSON.parse(raw);return{...defaultDb,games:Array.isArray(games)?games:[]}}catch{return defaultDb}}
async function readDb(){if(USE_SUPABASE)return readSupabaseDb();await ensureDb();return normalizeDb(JSON.parse(await fs.readFile(DB_FILE,"utf8")))}
async function writeDb(db){if(USE_SUPABASE){await writeSupabaseDb(db);return}await fs.mkdir(DATA_DIR,{recursive:true});const tmp=`${DB_FILE}.tmp`;await fs.writeFile(tmp,JSON.stringify(db,null,2));await fs.rename(tmp,DB_FILE)}
function supabaseHeaders(extra={}){return{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...extra}}
async function supabaseFetch(pathname,options={}){const baseUrl=SUPABASE_URL.replace(/\/rest\/v1\/?$/,"").replace(/\/$/,"");const response=await fetch(`${baseUrl}/rest/v1${pathname}`,{...options,headers:supabaseHeaders(options.headers||{})});if(!response.ok)throw new Error(`Erro no Supabase: ${response.status} ${await response.text()}`);return response}
async function readSupabaseDb(){const rows=await(await supabaseFetch("/app_state?id=eq.main&select=data")).json();if(rows[0]?.data)return normalizeDb(rows[0].data);const db=await initialDb();await writeSupabaseDb(db);return db}
async function writeSupabaseDb(db){await supabaseFetch("/app_state?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({id:"main",data:normalizeDb(db)})})}
function sendJson(res,status,payload){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(payload))}
function sendError(res,status,message){sendJson(res,status,{error:message})}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").map(p=>p.trim()).filter(Boolean).map(p=>{const i=p.indexOf("=");return i===-1?[p,""]:[p.slice(0,i),decodeURIComponent(p.slice(i+1))]}))}
function isAdmin(req){const token=parseCookies(req).bolao_admin;return Boolean(token&&sessions.has(token))}
function requireAdmin(req,res){if(!isAdmin(req)){sendError(res,401,"Login de administrador necessario.");return false}return true}
function readBody(req){return new Promise((resolve,reject)=>{let body="";req.on("data",chunk=>{body+=chunk;if(body.length>1024*1024){reject(new Error("Corpo muito grande."));req.destroy()}});req.on("end",()=>{if(!body)return resolve({});try{resolve(JSON.parse(body))}catch{reject(new Error("JSON invalido."))}});req.on("error",reject)})}
function normalizeName(name){return String(name||"").trim().replace(/\s+/g," ")}
function normalizeScore(value){const number=Number(value);return Number.isInteger(number)&&number>=0&&number<=99?number:null}
function matchOutcome(home,away){return home===away?"draw":home>away?"home":"away"}
function scorePrediction(prediction,game){if(!game||game.homeScore==null||game.awayScore==null)return 0;if(prediction.homeScore===game.homeScore&&prediction.awayScore===game.awayScore)return 5;return matchOutcome(prediction.homeScore,prediction.awayScore)===matchOutcome(game.homeScore,game.awayScore)?3:0}
function buildStandings(db){const gameMap=new Map(db.games.map(g=>[g.id,g]));return db.players.map(player=>{const pp=db.predictions.filter(p=>p.playerId===player.id);let points=0,exact=0,outcome=0;for(const p of pp){const partial=scorePrediction(p,gameMap.get(p.gameId));points+=partial;if(partial===5)exact++;if(partial===3)outcome++}return{id:player.id,name:player.name,points,exact,outcome,predictionsCount:pp.length,createdAt:player.createdAt}}).sort((a,b)=>b.points-a.points||b.exact-a.exact||a.name.localeCompare(b.name,"pt-BR"))}
function publicGame(g){return{id:g.id,stage:g.stage,group:g.group,venue:g.venue,homeTeam:g.homeTeam,awayTeam:g.awayTeam,startsAt:g.startsAt,status:g.status,homeScore:g.homeScore,awayScore:g.awayScore}}
function publicState(db){return{games:db.games.map(publicGame).sort(sortGames),standings:buildStandings(db),playersCount:db.players.length,storage:storageInfo(),scoring:{exact:5,outcome:3}}}
function storageInfo(){return USE_SUPABASE?{mode:"Supabase",persistent:true,message:"Os dados estao sendo salvos no Supabase."}:{mode:"Arquivo local",persistent:Boolean(process.env.DATA_DIR||process.env.DB_FILE),message:"Os dados estao sendo salvos em arquivo local. Em hospedagem gratuita, eles podem sumir quando o app reiniciar."}}
function publicPlayerEntry(db,player){const map=new Map(db.predictions.filter(p=>p.playerId===player.id).map(p=>[p.gameId,p]));return{id:player.id,name:player.name,createdAt:player.createdAt,locked:player.locked,predictions:db.games.map(publicGame).sort(sortGames).map(game=>{const p=map.get(game.id);return{game,homeScore:p?p.homeScore:null,awayScore:p?p.awayScore:null,pointsNow:p?scorePrediction(p,game):0}})}}
function sortGames(a,b){return(a.startsAt||"").localeCompare(b.startsAt||"")||a.homeTeam.localeCompare(b.homeTeam,"pt-BR")}
function validateGamePayload(payload,partial=false){const game={};for(const field of["stage","group","venue","homeTeam","awayTeam","startsAt","status"])if(payload[field]!==undefined)game[field]=String(payload[field]||"").trim();if((!partial||payload.homeTeam!==undefined)&&!game.homeTeam)throw new Error("Informe o time mandante.");if((!partial||payload.awayTeam!==undefined)&&!game.awayTeam)throw new Error("Informe o time visitante.");if(game.status&&!['upcoming','live','final'].includes(game.status))throw new Error("Status do jogo invalido.");if(payload.homeScore!==undefined)game.homeScore=payload.homeScore===""||payload.homeScore===null?null:normalizeScore(payload.homeScore);if(payload.awayScore!==undefined)game.awayScore=payload.awayScore===""||payload.awayScore===null?null:normalizeScore(payload.awayScore);if(game.homeScore===null&&payload.homeScore!==""&&payload.homeScore!==null&&payload.homeScore!==undefined)throw new Error("Placar do mandante invalido.");if(game.awayScore===null&&payload.awayScore!==""&&payload.awayScore!==null&&payload.awayScore!==undefined)throw new Error("Placar do visitante invalido.");return game}
async function handleApi(req,res,url){const method=req.method||"GET";
if(method==="GET"&&url.pathname==="/api/state")return sendJson(res,200,publicState(await readDb()));
if(method==="GET"&&url.pathname.startsWith("/api/games/")&&url.pathname.endsWith("/predictions")){const gameId=url.pathname.split("/")[3],db=await readDb(),game=db.games.find(x=>x.id===gameId);if(!game)return sendError(res,404,"Jogo nao encontrado.");const predictions=db.predictions.filter(p=>p.gameId===gameId).map(p=>{const player=db.players.find(x=>x.id===p.playerId);return{playerId:p.playerId,playerName:player?player.name:"Participante removido",homeScore:p.homeScore,awayScore:p.awayScore,pointsNow:scorePrediction(p,game)}}).sort((a,b)=>b.pointsNow-a.pointsNow||a.playerName.localeCompare(b.playerName,"pt-BR"));return sendJson(res,200,{game:publicGame(game),predictions,hidden:false})}
if(method==="POST"&&url.pathname==="/api/players/lookup"){const payload=await readBody(req),db=await readDb(),name=normalizeName(payload.name);if(name.length<2)return sendError(res,400,"Digite seu nome para entrar no bolao.");const player=db.players.find(p=>p.name.toLowerCase()===name.toLowerCase());return sendJson(res,200,player?{exists:true,player:publicPlayerEntry(db,player)}:{exists:false,name,games:db.games.map(publicGame).sort(sortGames)})}
if(method==="POST"&&url.pathname==="/api/players"){const payload=await readBody(req),db=await readDb(),name=normalizeName(payload.name);if(name.length<2)return sendError(res,400,"Informe um nome com pelo menos 2 caracteres.");if(db.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return sendError(res,409,"Ja existe um participante com esse nome.");if(!db.games.length)return sendError(res,400,"O administrador precisa cadastrar os jogos antes dos palpites.");const incoming=Array.isArray(payload.predictions)?payload.predictions:[],byGame=new Map(incoming.map(p=>[p.gameId,p])),playerId=crypto.randomUUID(),predictions=[];for(const game of db.games){const p=byGame.get(game.id),homeScore=p?normalizeScore(p.homeScore):null,awayScore=p?normalizeScore(p.awayScore):null;if(homeScore===null||awayScore===null)return sendError(res,400,`Preencha o palpite de ${game.homeTeam} x ${game.awayTeam}.`);predictions.push({id:crypto.randomUUID(),playerId,gameId:game.id,homeScore,awayScore,createdAt:new Date().toISOString(),updatedByAdminAt:null})}db.players.push({id:playerId,name,createdAt:new Date().toISOString(),locked:true});db.predictions.push(...predictions);await writeDb(db);return sendJson(res,201,{ok:true,player:publicPlayerEntry(db,db.players.find(p=>p.id===playerId)),standings:buildStandings(db)})}
if(method==="POST"&&url.pathname==="/api/admin/login"){const p=await readBody(req);if(p.username!==ADMIN_USER||p.password!==ADMIN_PASSWORD)return sendError(res,401,"Usuario ou senha invalidos.");const token=crypto.randomBytes(32).toString("hex");sessions.set(token,Date.now());res.setHeader("Set-Cookie",`bolao_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`);return sendJson(res,200,{ok:true,user:ADMIN_USER})}
if(method==="POST"&&url.pathname==="/api/admin/logout"){const token=parseCookies(req).bolao_admin;if(token)sessions.delete(token);res.setHeader("Set-Cookie","bolao_admin=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0");return sendJson(res,200,{ok:true})}
if(method==="GET"&&url.pathname==="/api/admin/me")return sendJson(res,200,{authenticated:isAdmin(req),user:isAdmin(req)?ADMIN_USER:null});
if(url.pathname.startsWith("/api/admin/")){if(!requireAdmin(req,res))return;if(method==="GET"&&url.pathname==="/api/admin/export")return sendJson(res,200,await readDb());if(method==="GET"&&url.pathname==="/api/admin/players"){const db=await readDb();return sendJson(res,200,{players:db.players,predictions:db.predictions,games:db.games.map(publicGame).sort(sortGames)})}
if(method==="POST"&&url.pathname==="/api/admin/games"){try{const game=validateGamePayload(await readBody(req)),db=await readDb();db.games.push({id:crypto.randomUUID(),stage:game.stage||"Fase de grupos",group:game.group||"",venue:game.venue||"",homeTeam:game.homeTeam,awayTeam:game.awayTeam,startsAt:game.startsAt||"",status:game.status||"upcoming",homeScore:game.homeScore??null,awayScore:game.awayScore??null,createdAt:new Date().toISOString()});await writeDb(db);return sendJson(res,201,publicState(db))}catch(e){return sendError(res,400,e.message)}}
if(method==="POST"&&url.pathname==="/api/admin/games/import"){const payload=await readBody(req),rows=String(payload.csv||"").split(/\r?\n/).map(r=>r.trim()).filter(Boolean);if(!rows.length)return sendError(res,400,"Cole pelo menos uma linha de jogos.");const db=await readDb();let imported=0;for(const row of rows){const sep=row.includes(";")?";":",",[stage,group,startsAt,homeTeam,awayTeam,venue]=row.split(sep).map(x=>String(x||"").trim());if(!homeTeam||!awayTeam)continue;db.games.push({id:crypto.randomUUID(),stage:stage||"Fase de grupos",group:group||"",venue:venue||"",startsAt:startsAt||"",homeTeam,awayTeam,status:"upcoming",homeScore:null,awayScore:null,createdAt:new Date().toISOString()});imported++}await writeDb(db);return sendJson(res,201,{imported,state:publicState(db)})}
const gm=url.pathname.match(/^\/api\/admin\/games\/([^/]+)$/);if(gm&&method==="PATCH"){try{const updates=validateGamePayload(await readBody(req),true),db=await readDb(),game=db.games.find(x=>x.id===gm[1]);if(!game)return sendError(res,404,"Jogo nao encontrado.");Object.assign(game,updates,{updatedAt:new Date().toISOString()});await writeDb(db);return sendJson(res,200,publicState(db))}catch(e){return sendError(res,400,e.message)}}if(gm&&method==="DELETE"){const db=await readDb();db.games=db.games.filter(g=>g.id!==gm[1]);db.predictions=db.predictions.filter(p=>p.gameId!==gm[1]);await writeDb(db);return sendJson(res,200,publicState(db))}
const pm=url.pathname.match(/^\/api\/admin\/players\/([^/]+)$/);if(pm&&method==="PATCH"){const payload=await readBody(req),db=await readDb(),player=db.players.find(x=>x.id===pm[1]);if(!player)return sendError(res,404,"Participante nao encontrado.");const name=normalizeName(payload.name);if(name.length>=2)player.name=name;if(Array.isArray(payload.predictions))for(const item of payload.predictions){const p=db.predictions.find(x=>x.playerId===player.id&&x.gameId===item.gameId),h=normalizeScore(item.homeScore),a=normalizeScore(item.awayScore);if(!p||h===null||a===null)continue;p.homeScore=h;p.awayScore=a;p.updatedByAdminAt=new Date().toISOString()}await writeDb(db);return sendJson(res,200,{ok:true,state:publicState(db)})}if(pm&&method==="DELETE"){const db=await readDb();db.players=db.players.filter(p=>p.id!==pm[1]);db.predictions=db.predictions.filter(p=>p.playerId!==pm[1]);await writeDb(db);return sendJson(res,200,publicState(db))}}
sendError(res,404,"Rota nao encontrada.")}
async function serveStatic(req,res,url){let relativePath=decodeURIComponent(url.pathname);if(relativePath==="/")relativePath="/index.html";const filePath=path.normalize(path.join(PUBLIC_DIR,relativePath));if(!filePath.startsWith(PUBLIC_DIR)){res.writeHead(403);return res.end("Acesso negado")}try{const content=await fs.readFile(filePath);res.writeHead(200,{"Content-Type":mimeTypes[path.extname(filePath)]||"application/octet-stream"});res.end(content)}catch{res.writeHead(404,{"Content-Type":"text/plain; charset=utf-8"});res.end("Arquivo nao encontrado")}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);try{if(url.pathname.startsWith("/api/"))return await handleApi(req,res,url);await serveStatic(req,res,url)}catch(e){sendError(res,500,e.message||"Erro interno.")}});
ensureDb().then(()=>server.listen(PORT,()=>console.log(`Bolao da Copa rodando em http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
